//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Clc_AppEntities : DbContext
    {
        public Clc_AppEntities()
            : base("name=Clc_AppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_BP> Tbl_BP { get; set; }
        public virtual DbSet<Tbl_Disease> Tbl_Disease { get; set; }
        public virtual DbSet<Tbl_Medicine> Tbl_Medicine { get; set; }
        public virtual DbSet<Tbl_Patient> Tbl_Patient { get; set; }
        public virtual DbSet<Tbl_Role> Tbl_Role { get; set; }
        public virtual DbSet<Tbl_Users> Tbl_Users { get; set; }
    }
}
