//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BP
    {
        public int BP_Id { get; set; }
        public Nullable<int> Systolic { get; set; }
        public string Diastolic { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
