//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Medicine
    {
        public int Medicine_Id { get; set; }
        public string Medicine_Name { get; set; }
        public string Medicine_Dosage { get; set; }
    }
}
